import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import java.io.File

plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

dependencies {
    implementation(projects.shared)

    implementation(compose.desktop.currentOs)
    implementation(libs.kotlinx.coroutinesSwing)

    implementation(libs.compose.uiToolingPreview)
    implementation(libs.kotlinx.serialization.json)
}

compose.desktop {
    application {
        mainClass = "xyz.kbrowser.MainKt"
        jvmArgs += listOf(
            "--enable-native-access=jcef",
            "--add-opens=jcef/com.jetbrains.cef.remote.browser=ALL-UNNAMED",
            "--add-opens=jcef/com.jetbrains.cef.remote=ALL-UNNAMED"
        )

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "xyz.kbrowser"
            packageVersion = "1.0.0"
        }
    }
}

// Integration tests: each is a `fun main()` that drives a real JCEF browser and
// exits non-zero on failure, so they double as JavaExec tasks.
val testJvmArgs = listOf(
    "--enable-native-access=jcef",
    "--add-opens=jcef/com.jetbrains.cef.remote.browser=ALL-UNNAMED",
    "--add-opens=jcef/com.jetbrains.cef.remote=ALL-UNNAMED"
)

fun registerKBrowserTest(name: String, mainClass: String) {
    tasks.register<JavaExec>(name) {
        group = "application"
        this.mainClass.set(mainClass)
        val compileTestKotlin = tasks.named("compileTestKotlin")
        classpath = files(compileTestKotlin, configurations.named("testRuntimeClasspath"))
        jvmArgs(testJvmArgs)
        workingDir = rootProject.projectDir
    }
}

registerKBrowserTest("runFileUploadTest", "xyz.kbrowser.FileUploadTestKt")
registerKBrowserTest("runTimingLoadTest", "xyz.kbrowser.TimingLoadTestKt")
registerKBrowserTest("runNonOsrLoadHtmlTest", "xyz.kbrowser.NonOsrLoadHtmlTestKt")
registerKBrowserTest("runNonOsrUiLoadTest", "xyz.kbrowser.NonOsrUiLoadTestKt")
registerKBrowserTest("runDiagNonOsr", "xyz.kbrowser.DiagNonOsrKt")
registerKBrowserTest("runResizeFollowTest", "xyz.kbrowser.ResizeFollowTestKt")
registerKBrowserTest("runNonOsrResizeTest", "xyz.kbrowser.NonOsrResizeTestKt")
registerKBrowserTest("runKBDebugTest", "xyz.kbrowser.KBDebugTestKt")

// MCP server over stdio: the AI client launches this directly as its MCP command.
tasks.register<JavaExec>("runMcpServer") {
    group = "application"
    description = "KBrowser MCP server (stdio) — point your MCP client at this task"
    mainClass.set("xyz.kbrowser.mcp.McpMainKt")
    classpath = sourceSets["main"].runtimeClasspath
    jvmArgs(testJvmArgs)
    workingDir = rootProject.projectDir
    standardInput = System.`in`
}

// Prebuilt launcher for MCP clients: compiles once, then the generated script
// starts the server with plain `java` — no Gradle at startup.
tasks.register("exportMcpLaunch") {
    group = "application"
    description = "Generate a standalone MCP launcher script (no Gradle at startup)"
    dependsOn(tasks.named("compileKotlin"))
    val scriptPath = layout.buildDirectory.file("mcp/run-mcp-server.sh").get().asFile.absolutePath
    val cp = sourceSets["main"].runtimeClasspath.asPath
    val root = rootProject.projectDir.absolutePath
    val jvmArgsStr = testJvmArgs.joinToString(" ")
    doLast {
        val f = File(scriptPath)
        f.parentFile.mkdirs()
        f.writeText(
            """
            #!/bin/bash
            # Generated by: ./gradlew :desktopApp:exportMcpLaunch
            # KBrowser MCP server (stdio). Re-run the gradle task above after code changes.
            cd "$root"
            exec java $jvmArgsStr -cp "$cp" xyz.kbrowser.mcp.McpMainKt
            """.trimIndent() + "\n"
        )
        f.setExecutable(true)
        println("MCP launcher written to: $scriptPath")
    }
}
