package xyz.kbrowser.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Scans the composeResources/font/ directory for font files
 * and generates a Kotlin file with the list of font resource paths.
 */
abstract class GenerateFontPathsTask : DefaultTask() {

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val fontDirPath: Property<String>

    @get:Input
    abstract val packageName: Property<String>

    @TaskAction
    fun generate() {
        val dir = File(fontDirPath.get())
        val fontExtensions = setOf("ttf", "otf", "woff", "woff2")
        val paths = mutableListOf<String>()

        if (dir.exists() && dir.isDirectory) {
            dir.walkTopDown().forEach { file ->
                if (file.isFile && file.extension.lowercase() in fontExtensions) {
                    val relativePath = file.relativeTo(dir.parentFile).path.replace("\\", "/")
                    paths.add(relativePath)
                }
            }
        }

        paths.sort()

        val pkg = packageName.get()
        val outFile = File(outputDir.get().asFile, "FontPaths.generated.kt")

        val content = buildString {
            appendLine("// AUTO-GENERATED by GenerateFontPathsTask. Do not edit manually.")
            appendLine("package $pkg")
            appendLine()
            if (paths.isEmpty()) {
                appendLine("internal val generatedFontPaths: List<String> = emptyList()")
            } else {
                appendLine("internal val generatedFontPaths: List<String> = listOf(")
                for (path in paths) {
                    appendLine("    \"$path\",")
                }
                appendLine(")")
            }
        }

        outFile.parentFile.mkdirs()
        outFile.writeText(content)

        logger.lifecycle("[GenerateFontPaths] Found ${paths.size} font(s): ${paths.joinToString(", ")}")
    }
}
